"""added likes to centers

Revision ID: 76182ba6f9cb
Revises: f9181128cfc4
Create Date: 2025-01-06 11:05:24.239295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76182ba6f9cb'
down_revision = 'f9181128cfc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recycling_center', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recycling_center', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
